name: Keep Bot Alive

on:
  schedule:
    - cron: "*/5 * * * *" # a cada 5 minutos
  workflow_dispatch: # rodar manualmente

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Vercel
        run: |
          curl -s "https://clinica-gabriela-bot.vercel.app/api/ping?token=${{ secrets.PING_TOKEN }}"

